### PR TITLE
Upgrade spot to use rspotify

### PR DESCRIPTION
**Pull request by estiens**
Spotify's metadata API and the meta-spotify gem are both deprecated (https://github.com/philnash/meta-spotify/issues/10)

Recently, we began having troubles querying spotify through hubot. This PR fixes those issues by upgrading the Spot script to use rspotify instead of meta-spotify. All returned data should remain the same, thus no changes to spot.coffee are required.

NB: There are currently problems with this script caused by Spotify screwing up Applescript support on their [latest release.](https://community.spotify.com/t5/Help-Desktop-Linux-Mac-and/AppleScript-support-removed-with-update-1-0-1-1060-gc75ebdfd/m-p/1041430/highlight/true#M111610) - There are workarounds, however it appears the "play track"  command is not currently supported. There may need to be further changes to this script to make it fully functional once Spotify re-instates Applescript functionality. However, this fully works for querying songs and albums as before.

### CODE REVIEW

**Comment by estiens** [comment]
two more tiny fixes. convert ms to seconds so that track time is shown correctly in the chatroom, and sort correctly by popularity

**Comment by estiens** [comment]
Also, problems with Spotify can be fixed by doing the following.

1) Download the last version of Spotify here(https://www.dropbox.com/s/zlntkpzq6ysmk9c/Spotify.dmg?dl=0) and copy it into Applications

2) Get info on the app from the Finder and click "locked" so it won't be auto-upgraded

Viola - old Spotify with working Applescript + new Spot client using rspotify restores all functionality

**Comment by minton** [comment]
Nice work! :+1: :star: 

Thanks for making it more idiomatic ruby. As you can probably guess ruby isn't my native language.

Just tested this and it works great. Hopefully Spotify will un-break their Applescript support.

**Comment by estiens** [comment]
Thanks!

Just a note for anyone downgrading Spotify - locking the app does /not/ keep it from auto-updating :angry: Here are [instructions](https://community.spotify.com/t5/Help-Desktop-Linux-Mac-and/Revert-back-to-Spotify-0-8-5-on-Mac/m-p/325476/highlight/true#M35698) on how to keep the app from auto-updating until they reinstate applescript support.

**Comment by peterborghard** [comment]
spotify downgrade(dropbox) worked great for me!

**Pull request merged**
